name = "NRI Modpack"
author = "ErinBN"
version = "5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8c0d73b46314ac13bbc84933555e19b7c131b8d8249e5cac6af2889b13f3e00"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
