name = "NRI Modpack"
author = "ErinBN"
version = "5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3f6ec3ac1c876df540c9cb49c47dc91df89082ff011961ee0195b9c15289621"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
