name = "NRI Modpack"
author = "ErinBN"
version = "5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfa5ece0737a62622c76db25dbf02444d2d62af74efc86cd20bb1ef69b16fa7c"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
